#ifndef PARAMETER_HPP
#define PARAMETER_HPP

#define DEPTH_FRAME_WIDTH 320
#define DEPTH_FRAME_HEIGHT 240

#define COLOR_FRAME_WIDTH 960
#define COLOR_FRAME_HEIGHT 540

#define MINIMUM_DISTANCE 0.2
#define MAXIMUM_DISTANCE 1.0

#define DEPTH_IMAGE_TOPIC "depth_image"
#define COLOR_IMAGE_TOPIC "color_image"

#define PUBLISH_DEPTH true
#define PUBLISH_COLOR true

#endif // PARAMETER_HPP